config/routes.rb
Rails.application.routes.draw do
  resources :swapeople
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/swaperson.rb
class Swaperson < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  after_create_commit { broadcast_prepend_to "tweets" }
  after_update_commit { broadcast_replace_to "tweets" }
  after_destroy_commit { broadcast_remove_to "tweets" }

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/swapeople_controller.rb
class SwapeopleController < ApplicationController
  before_action :set_swaperson, only: %i[ show edit update destroy ]
  before_action :set_swapeople, only: %i[ index ]

  # GET /swapeople or /swapeople.json
  def index
  end

  # GET /swapeople/1 or /swapeople/1.json
  def show
  end

  # GET /swapeople/new
  def new
    @swaperson = Swaperson.new
  end

  # GET /swapeople/1/edit
  def edit
  end

  # POST /swapeople or /swapeople.json
  def create
    @swaperson = Swaperson.new(swaperson_params)

    respond_to do |format|
      if @swaperson.save
        format.html { redirect_to swaperson_url(@swaperson), notice: "Swaperson was successfully created." }
        format.json { render :show, status: :created, location: @swaperson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @swaperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swapeople/1 or /swapeople/1.json
  def update
    respond_to do |format|
      if @swaperson.update(swaperson_params)
        format.html { redirect_to swaperson_url(@swaperson), notice: "Swaperson was successfully updated." }
        format.json { render :show, status: :ok, location: @swaperson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @swaperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swapeople/1 or /swapeople/1.json
  def destroy
    @swaperson.destroy!

    respond_to do |format|
      format.html { redirect_to swapeople_url, notice: "Swaperson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swaperson
      @swaperson = SwapersonService.new(params[:person_id]).call
    end

    def set_swapeople
      @swapeople = SwapeopleService.call
    end

    # Only allow a list of trusted parameters through.
    def swaperson_params
      params.fetch(:swaperson, {})
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/swapeople_helper.rb
module SwapeopleHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turbo Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/swapeople/_form.html.erb
<%= form_with(model: swaperson) do |form| %>
  <% if swaperson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(swaperson.errors.count, "error") %> prohibited this swaperson from being saved:</h2>

      <ul>
        <% swaperson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/swapeople/_swaperson.html.erb
<div id="<%= dom_id swaperson %>">
</div>

app/views/swapeople/edit.html.erb
<% content_for :title, "Editing swaperson" %>

<h1>Editing swaperson</h1>

<%= render "form", swaperson: @swaperson %>

<br>

<div>
  <%= link_to "Show this swaperson", @swaperson %> |
  <%= link_to "Back to swapeople", swapeople_path %>
</div>

app/views/swapeople/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Swapeople" %>

<h1>Swapeople</h1>

<div id="swapeople">
  <% @swapeople.each do |swaperson| %>
    <%= render swaperson %>
    <p>
      <%= link_to "Show this swaperson", swaperson %>
    </p>
  <% end %>
</div>

<%= link_to "New swaperson", new_swaperson_path %>

app/views/swapeople/new.html.erb
<% content_for :title, "New swaperson" %>

<h1>New swaperson</h1>

<%= render "form", swaperson: @swaperson %>

<br>

<div>
  <%= link_to "Back to swapeople", swapeople_path %>
</div>

app/views/swapeople/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @swaperson %>

<div>
  <%= link_to "Edit this swaperson", edit_swaperson_path(@swaperson) %> |
  <%= link_to "Back to swapeople", swapeople_path %>

  <%= button_to "Destroy this swaperson", @swaperson, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
    <% if tweet.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>

      <div class="field mb-3">
        <%= form.label :body, class: 'form-label' %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div class="card card-body">
    <div><%= tweet.body %></div>
    <div class="mt-2">
      Likes (0)
      Retweets (0)

      <%= link_to "Edit", edit_tweet_path(tweet) %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= turbo_frame_tag dom_id(@tweet) do %>
  <% content_for :title, "Editing tweet" %>

  <h3>Editing tweet</h3>
  <div>
    <%= render "tweets/form", tweet: @tweet %>
    <%= link_to 'Cancel', @tweet %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<%= turbo_stream_from "tweets" %>
<%= turbo_frame_tag "tweets" do %>
  <p style="color: green"><%= notice %></p>

  <% content_for :title, "Tweets" %>

  <h1>Tweets</h1>

  <div id="tweets">
    <%= @tweets.each do |tweet| %>
      <%= render "tweets/tweet", tweet: tweet %>
      <p>
        <%= link_to "Show this tweet", tweet_path(tweet) %>
      </p>
    <% end %>
  </div>
  <br>
  <%= link_to "New tweet", new_tweet_path %>
<% end %>

app/views/tweets/new.html.erb
<% content_for :title, "New tweet" %>

<h1>New tweet</h1>

<%= render "tweets/form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p id="notice" style="color: green"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>

<%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
<%= link_to "Back to tweets", tweets_path %>